# Compose script to spin up posgres db on Docker

version: '3.9'

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: abc_dba
      POSTGRES_PASSWORD: password
      POSTGRES_DB: abc
    ports:
      - "5454:5454"